### ISSUE TITLE
bug: Bluetooth makes uart communication lag

### ISSUE THREAD

**Issue by AdneHK96** [MithalAS/BlueOS#5]
### Bug description

When doing remote motor controller updates we connect to the controllers using socat tcp stream on the respective /dev/tty* port. 
This can be very unstable especially for the standard port serial0 as this is shared with Bluetooth. 

### Steps to reproduce

1. ssh into a pi
2. make tcp stream with "socat tcp-listen:65108,reuseaddr,fork file:/dev/serial0,raw &"
3. try to connect to this port via vesc control 

### Primary pain point(s)

Cant upload new firmware on motor controllers. 

### Additional context

A solution for this is to add "dtoverlay=disable-bt" to the config.txt as standard. In the same way dtoverlay=uart1, 3, 4 and 5 gets added by blueos. might also need to change the standard serial port configurator for serial 1 from /dev/ttyS0 to /dev/ttyAMA0.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by goasChris** [comment]
Hmm, interesting. Yeah, I don't see us ever needing bluetooth, so I'm happy to disable it. I assume we can simply add it here? 
https://github.com/MithalAS/BlueOS/blob/02eb2cf5e1ef396cb59ac824e4ec3cc51e8c96eb/install/boards/bcm_2712.sh#L25-L35

Assuming that is the correct board of course.

**Comment by AdneHK96** [comment]
> Hmm, interesting. Yeah, I don't see us ever needing bluetooth, so I'm happy to disable it. I assume we can simply add it here?
> 
> https://github.com/MithalAS/BlueOS/blob/02eb2cf5e1ef396cb59ac824e4ec3cc51e8c96eb/install/boards/bcm_2712.sh#L25-L35
> 
> Assuming that is the correct board of course.

Seams like it. As well as changing the default serial board configurator.

**Comment by goasChris** [comment]
Work with Ådne on this. Needs to experimenting and testing

**Comment by goasChris** [comment]
Add dtoverlay string, test to see if new serial config is now avaliable. Hack board again, if need

**Comment by goasChris** [comment]
Fixed in https://github.com/MithalAS/BlueOS/commit/322bcd49058b9100fd4bbfd51284af6f488ea384
